---
title: "Trade_off"
author: "Khanh Duong"
date: "2024-11-12"
output: html_document
---

**Please set working directory before running these codes.**

```{r data}

library(readxl)
library(dplyr)

LIS2024 <- read_excel("LIS2024.xlsx") %>%
  mutate(gini_disp = Disposable * 100, gini_mkt = Market * 100) %>%
  select(Country_code = Code, year = Year, gini_disp, gini_mkt) %>%
  mutate(redistribution = gini_mkt - gini_disp) %>%
  mutate(year = as.character(year))

pwt1001 <- read_excel("pwt1001.xlsx", sheet = "Data") %>%
  select(Country_code = countrycode, year, human_capital = hc, technology = ctfp) %>%
  mutate(year = as.character(year))

world_bank <- read_excel("world_bank.xlsx") %>%
  select(
    Country_code = `Country Code`,
    year = `Time Code`,
    GDP_per_capita = `NY.GDP.PCAP.KD`,
    trade = `NE.TRD.GNFS.ZS`,
    FDI = `BX.KLT.DINV.WD.GD.ZS`,
    credit = `FS.AST.PRVT.GD.ZS`,
    fertility = `SP.DYN.TFRT.IN`,
    unemployment = `SL.UEM.TOTL.ZS`,
    inflation = `FP.CPI.TOTL.ZG`
  ) %>%
  mutate(year = gsub("YR", "", as.character(year)))

# Merge datasets by 'Country_code' and 'year'
data <- pwt1001 %>%
  left_join(world_bank, by = c("Country_code", "year")) %>%
  left_join(LIS2024, by = c("Country_code", "year"))

# Load and merge country metadata, filter out rows with missing values in key columns
data0 <- data %>%
  filter(!is.na(GDP_per_capita), !is.na(gini_disp)) %>%
  rename(inequality = gini_disp)

data <- data0 %>%
  select(-Country_code, -year)

min_growth <- min(data$GDP_per_capita)
max_growth <- max(data$GDP_per_capita)

min_inequality <- min(data$inequality)
max_inequality <- max(data$inequality)

```


Load and Prepare the Data

```{r}
set.seed(0209)
# Load necessary libraries
library(dplyr)
library(caret)
library(glmnet)
library(mco)

# Define the predictors for the models

pre_process <- preProcess(data, method = c('bagImpute', 'range'))
data <- predict(pre_process, newdata = data)

predictors <- data %>%
  select(redistribution, human_capital, technology, trade, FDI, credit, fertility, unemployment, inflation) %>%
  as.matrix(.)

# Convert the columns to numeric, if needed
GDP_per_capita <- as.numeric(data$GDP_per_capita)
inequality <- as.numeric(data$inequality)
inequality_penalty <- data$inequality[which.max(data$GDP_per_capita)]

```

Train the Machine Learning Models (Elastic Net)

```{r message=TRUE}
# Set up cross-validation
control <- trainControl(
  method = "cv", 
  number = 5
)

tuneGrid = expand.grid(alpha = seq(0, 1, by = 0.1), lambda = 10^seq(-3, -2, length.out = 50))

# Train Elastic Net model for GDP per capita (growth)
model_growth <- train(
  predictors, GDP_per_capita,
  method = "glmnet",
  trControl = control,
  tuneGrid = tuneGrid,
  metric = "RMSE",
  na.action = na.omit
)

# Train Elastic Net model for inequality (Gini index)
model_inequality <- train(
  predictors, inequality,
  method = "glmnet",
  trControl = control,
  tuneGrid = tuneGrid,
  metric = "RMSE",
  na.action = na.omit
)

# Extract coefficients from the models
coefficients_growth <- matrix(coef(model_growth$finalModel, model_growth$bestTune$lambda), ncol = 1)
coefficients_inequality <- matrix(coef(model_inequality$finalModel, model_inequality$bestTune$lambda), ncol = 1)

```

Define the Optimisation Function

```{r}

objective_function <- function(x) {
  x_matrix <- matrix(x, nrow = 1)  # Convert input to a row matrix
  growth <- as.matrix(cbind(1, x_matrix) %*% coefficients_growth)
  inequality <- as.matrix(cbind(1, x_matrix) %*% coefficients_inequality)
  return(c(-growth, inequality))  # Maximize growth, minimize inequality
}

```


```{r}
res_income <- GDP_per_capita - as.matrix(cbind(1, predictors) %*% coefficients_growth)
res_inequality <- inequality - as.matrix(cbind(1, predictors) %*% coefficients_inequality)

cor_summary <- do.call(rbind, lapply(1:ncol(predictors), function(i) {
  test_income <- cor.test(res_income, predictors[, i], use = "complete.obs")
  test_ineq <- cor.test(res_inequality, predictors[, i], use = "complete.obs")
  c(colnames(predictors)[i], round(test_income$estimate, 3), round(test_income$p.value, 3), 
    round(test_ineq$estimate, 3), round(test_ineq$p.value, 3))
}))

colnames(cor_summary) <- c("Variable", "Correlation with Income", "P-value (Income)", "Correlation with Inequality", "P-value (Inequality)")

xtable::xtable(cor_summary)
```


Run the Multi-Objective Optimisation Using NSGA-II

```{r}
result <- nsga2(
  objective_function,
  idim = ncol(predictors),
  odim = 2,
  lower.bounds = rep(0, ncol(predictors)),
  upper.bounds = rep(1, ncol(predictors)),
  popsize = 10000
)

pareto_front <- as.data.frame(result$value) %>%
  setNames(c("GDP_per_capita", "inequality")) %>%
  transform(GDP_per_capita = -GDP_per_capita)

write.csv(pareto_front, "figs/pareto_front_lis.csv", row.names = FALSE)

```


```{r}
pareto_front <- read.csv("figs/pareto_front_lis.csv")
```


Slope from the Pareto Front

```{r}
trade_off_pareto <- lm(inequality ~ GDP_per_capita, data = pareto_front, subset = GDP_per_capita <= 1)
summary(trade_off_pareto)
slope <- trade_off_pareto[["coefficients"]][["GDP_per_capita"]]

trade_off_actual <- lm(inequality ~ GDP_per_capita, data = data, subset = inequality < 0.2)
intercept <- predict(trade_off_actual,data.frame(GDP_per_capita = 1))-slope

```


Distance from Choice

```{r}
data$distance <- abs(data$inequality - (slope * data$GDP_per_capita + intercept))

too_close_threshold <- 0.02
too_far_threshold <- 0.2

data$point_category <- ifelse(data$distance < too_close_threshold, "too_close",
                              ifelse(data$distance > too_far_threshold, "too_far", "Normal"))

plot_result1 <- ggplot() +
  geom_point(data = pareto_front, aes(x = GDP_per_capita, y = inequality), color = "orange") +
  geom_point(data = data, aes(x = GDP_per_capita, y = inequality, color = point_category)) + 
  geom_abline(intercept=intercept, slope=slope, color = "blue", linetype = "dashed") +
  theme_minimal() +
  labs(y = "Inequality", x = "Income", color = "Distance") +  
  xlim(0, 1) + 
  scale_color_manual(
    values = c("too_close" = "green", "too_far" = "red", "Normal" = "grey"),
    labels = c(
      "too_close" = paste("Close (<", too_close_threshold, ")", sep = ""),
      "too_far" = paste("Far (>", too_far_threshold, ")", sep = "")
    )
  )

plot_result1

```

Close to the Choice

```{r}

data$code <- data0$Country_code

data_too_near <- data[data$distance < too_close_threshold, ]

labels <- data_too_near %>%
  group_by(code) %>%
  slice(n())

library(ggrepel)

plot_result <- plot_result1 + geom_text_repel(data = labels, aes(x = GDP_per_capita, y = inequality, label = code), 
            hjust = -0.2, vjust = -0.5, size = 3, show.legend = FALSE)

plot_result

```


The trend lines

```{r}

trends <- ggplot(data, aes(x = GDP_per_capita, y = inequality)) +
  geom_point(alpha = 0.5, colour = "grey") + # Scatter points
  geom_smooth(data = subset(data, inequality < 0.2), aes(colour = "Inequality < 0.2"), method = "lm", se = FALSE) +
  geom_smooth(data = subset(data, GDP_per_capita < 0.2), aes(colour = "Income < 0.2"), method = "lm", se = FALSE) +
  labs(title = "",
       x = "Income", y = "Inequality", colour = "Linear trends") + xlim(0, 1) + ylim(0,1) +
  theme_minimal()

trends
```


```{r}
country_region <- read_excel("world_bank.xlsx", sheet = "Country - Metadata")
country_means <- data %>%
  group_by(code) %>%
  summarise(
    mean_GDP_per_capita = mean(GDP_per_capita, na.rm = TRUE),
    mean_inequality = mean(inequality, na.rm = TRUE)
  ) %>%
  left_join(country_region, by = c("code" = "Code"))

# Create the plot with one point per country
trends <- ggplot(country_means, aes(x = mean_GDP_per_capita, y = mean_inequality)) +
  geom_smooth(data = subset(country_means, mean_inequality < 0.2), 
              aes(linetype = "Inequality < 0.2"), color = "blue", method = "lm", se = FALSE) +
  geom_smooth(data = subset(country_means, mean_GDP_per_capita < 0.2), 
              aes(linetype = "Income < 0.2"), color = "red", method = "lm", se = FALSE) +
  geom_text_repel(aes(label = code, color = Region), size = 2) +  
  labs(title = "",
       x = "Mean Income (GDP per capita)", 
       y = "Mean Inequality", 
       color = "Region",   # Legend for text labels
       linetype = "Trend") +
  theme_minimal() + 
  xlim(0, 1) + ylim(0, 1) +
  scale_color_discrete() +
  scale_linetype_manual(values = c("Inequality < 0.2" = "solid", 
                                   "Income < 0.2" = "solid"))

trends

```


```{r fig.height=7, fig.width=10}
library(tidyr)

df_wide <- expand.grid(Country_code = unique(data0$Country_code), 
                       year = seq(min(data0$year, na.rm = TRUE), max(data0$year, na.rm = TRUE))) %>%
  left_join(data0[,1:2] %>% mutate(year = as.integer(year), present = 1), by = c("Country_code", "year")) %>%
  mutate(present = replace_na(present, 0)) %>%
  pivot_wider(names_from = Country_code, values_from = present, values_fill = list(present = 0))


library(ggplot2)
library(reshape2)

# Create the heatmap data
df_melted <- melt(df_wide, id.vars = "year", variable.name = "Country_code", value.name = "present")

# Plot the heatmap
panel <- ggplot(df_melted, aes(x = year, y = Country_code, fill = factor(present))) +
  geom_tile() +
  scale_fill_manual(values = c("transparent", "blue")) +
  scale_x_continuous(breaks = seq(min(df_melted$year), max(df_melted$year), by = 2)) +
  labs(x = "", y = "", fill = "Present Data") + theme_minimal() +
  theme(axis.text.x = element_text(angle = 90), # Rotate x-axis labels for readability
        axis.text.y = element_text(size = 8)) + guides(fill = FALSE)

panel

```




Output

```{r}
ggsave(file="figs/Lis.pdf", plot=plot_result, width=10, height=5)
ggsave(file="figs/trends.pdf", plot=trends, width=10, height=5)
ggsave(file="figs/panel.pdf", plot=panel, width=10, height=10)
write.csv(country_means, file="figs/country_means.csv", row.names = FALSE)


```
